local data = {}
data['player'] = {}
data['player']['collides'] = true
data['player']['x'] = 21.366169597606
data['player']['drawYOffset'] = -16
data['player']['y'] = 32.034794695212
data['player']['speed'] = 100
data['player']['spriteId'] = 'player_walk_up_5'
data['player']['timeSinceLastFrame'] = 0.066254536010092
data['player']['leftBlocked'] = false
data['player']['rightBlocked'] = false
data['player']['width'] = 20
data['player']['colliding'] = false
data['player']['cycleAnimation'] = false
data['player']['id'] = 'player'
data['player']['upBlocked'] = false
data['player']['state'] = 'walk_up'
data['player']['downBlocked'] = false
data['player']['frameCounter'] = 5
data['player']['framesPerSecond'] = 8
data['player']['oldX'] = 21.366169597606
data['player']['resetAnimation'] = false
data['player']['oldY'] = 32.034794695212
data['player']['drawXOffset'] = 0
data['player']['height'] = 10
data['player']['moved'] = false
return data