local data = {}
data[1] = {}
data[2] = {}
data[3] = {}
data[4] = {}
data[5] = {}
data[1]['amount'] = 1
data[1]['item'] = 'jug'
data[1]['shortcut'] = 'actionBar1'
data[2]['amount'] = 1
data[2]['item'] = 'seed'
data[2]['shortcut'] = 'actionBar2'
data[3]['amount'] = 0
data[3]['item'] = 'empty'
data[3]['shortcut'] = 'actionBar3'
data[4]['amount'] = 0
data[4]['item'] = 'empty'
data[4]['shortcut'] = 'actionBar4'
data[5]['amount'] = 0
data[5]['item'] = 'empty'
data[5]['shortcut'] = 'actionBar5'
return data
